# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Kevincxv.Messiah
PackageVersion: 2026.10.02.4
InstallerType: exe
Scope: machine
ElevationRequirement: elevatesSelf
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent
  SilentWithProgress: /silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Kevincxv/pc-setup-kit/releases/download/v2026.10.02.4/Messiah-Setup.exe
  InstallerSha256: 1DC28C5A70E9C2D63108FA65ED22646890AF00C8C6B556172A5E0B732A6088AE
ManifestType: installer
ManifestVersion: 1.9.0